[profile.default]
out = 'out'
src = 'src'
libs = ['lib']

solc = '0.8.20'

remapping = [
    'contracts/=lib/contracts/contracts/',
    'forge-std/=lib/forge-std/src/'
]

[rpc_endpoints]
hoodi = "https://rpc.hoodi.ethpandaops.io"

